
name: ${project.artifactId}
author: tWizT3d_dreaMr, TonyJamesStark
version: ${project.version}
main: me.tWizT3d_dreaMr.FallingCrate.main
commands:
   fallcrate:
      description: Makes a falling crate.
      usage: /fallcrate keyname
   setfallcrate:
      description: Makes a falling crate.
      usage: setfallcrate x1 y1 z1 x2 y2 z2
   togglefallcrateevent:
      description: Makes a falling crate.
      usage: togglefallcrateeventFCChestSet
   FCChestSet:
      description: Makes a falling crate chest
      usage: FCChestSet cratename x y z (note coords are relative to command block)
   cratesay:
      description: Sends a message to all people in the arena.
      usage: cratesay <message>
permissions:
  tCrate.create:
    default: op
    description: Allows the player to make a falling crate.
depends: [tWizT3dLib]
api-version: 1.21.4
